use_frameworks!

platform :ios, '9.0'
inhibit_all_warnings!

target 'BoostSwift_Example' do
  pod 'BoostSwift', :path => '../'

  target 'BoostSwift_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3.2'
    pod 'Nimble', '~> 7.3.1'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.9.0'
  end
end
